version: '3.8'
services:
  redis:
    container_name: hotels_redis
    image: redis
    ports:
      - '6379:6379'
  db:
    image: postgres:14.5
    container_name: hotels_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_hotels
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'

volumes:
  pg_data:
  pgadmin_data:
