version: '3.8'

services:
  redis:
    container_name: booking_redis
    image: redis:7
    ports:
      - '6379:6379'

  db:
    image: postgres:15
    container_name: booking_db
    env_file:
      - .env.dev
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    container_name: booking_pgadmin
    env_file:
      - .env.dev
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'

volumes:
  pg_data:
  pgadmin_data:
